name: Update badges

on:
  schedule:
    # Runs at 17:30 UTC every day
    - cron: "30 17 * * *"

jobs:
  update-readme:
    timeout-minutes: 10
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CREDLY_USER: miguel-borges
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
