name: Update badges

on:
# Runs at 0am UTC every day 1 of each month
  schedule:
    
    - cron: "0 0 1 * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
